server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: GAME-SERVICE
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game/**
